version: '2.4'

name: bugbountylab
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - bb-db

  bb-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bb-labs
      MYSQL_USER: bb-labs-user
      MYSQL_PASSWORD: bb-labs-password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${PORT}:3306"

  ssti-web:
    build:
      context: .
      dockerfile: Dockerfile-SSTI
    ports:
      - "${PORT}:8080"
    volumes:
      - ./ssti-labs:/var/www/html
    depends_on:
      - bb-db

volumes:
  db_data:
